name: theheck
version: stable
version-script: git -C parts/theheck/build describe --abbrev=0 --tags
summary: Magnificent app which corrects your previous console command.
description: |
  The Heck tries to match a rule for the previous command,
  creates a new command using the matched rule and runs it.

grade: stable
confinement: classic

apps:
  theheck:
    command: bin/theheck
    environment:
        PYTHONIOENCODING: utf-8
  heck:
    command: bin/heck
    environment:
        PYTHONIOENCODING: utf-8

parts:
  theheck:
    source: https://github.com/nvbn/theheck.git
    plugin: python
